import V1 from 'assets/img/personal_works/v_1.jpg'
import V2 from 'assets/img/personal_works/v_2.jpg'
import V3 from 'assets/img/personal_works/v_3.jpg'
import V4 from 'assets/img/personal_works/v_4.jpg'
import V5 from 'assets/img/personal_works/v_5.jpg'
import V6 from 'assets/img/personal_works/v_6.jpg'
import V7 from 'assets/img/personal_works/v_7.jpg'
import V8 from 'assets/img/personal_works/v_8.jpg'
import V9 from 'assets/img/personal_works/v_9.jpg'
import V10 from 'assets/img/personal_works/v_10.jpg'
import V11 from 'assets/img/personal_works/v_11.jpg'
import V12 from 'assets/img/personal_works/v_12.jpg'
import V13 from 'assets/img/personal_works/v_13.jpg'
import V14 from 'assets/img/personal_works/v_14.jpg'
import V15 from 'assets/img/personal_works/v_15.jpg'
import V16 from 'assets/img/personal_works/v_16.jpg'
import V17 from 'assets/img/personal_works/v_17.jpg'

export const personalWorksData = [V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17]
